### PR TITLE
[WIP] Replace all `apt` with `apt-get`.

### PR DESCRIPTION
**Pull request by KexyBiscuit**
## See also

[SCRIPT USAGE AND DIFFERENCES FROM OTHER APT TOOLS - Ubuntu Manpage: apt - command-line interface](https://manpages.ubuntu.com/manpages/disco/en/man8/apt.8.html#script%20usage%20and%20differences%20from%20other%20apt%20tools)

### CODE REVIEW

**Comment by LionNatsu** [comment]
I am not familiar to these command line tools, need help, cc @MingcongBai .
BTW, have you test this?

**Comment by KexyBiscuit** [comment]
@LionNatsu Minimal test shows no problem.

**Comment by eatradish** [comment]
> I am not familiar to these command line tools, need help, cc @MingcongBai .
> BTW, have you test this?

> They are very similar command line tools available in Trusty. apt-get and apt-cache's most commonly used commands are available in apt.

apt-get may be considered as lower-level and "back-end", and support other APT-based tools. apt is designed for end-users (human) and its output may be changed between versions. 

from [Ask Ubuntu](https://askubuntu.com/questions/445384/what-is-the-difference-between-apt-and-apt-get)

**Comment by liushuyu** [comment]
Staled PR?
Also, `apt` is not suitable for scripting, `acbs` and `autobuild` have already switched to use `apt-get`.

**Pull request merged**
